# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equ_courses_disp.ui'
#
# Created: Mon Apr 23 15:04:20 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_equi_course_disp(object):
    def setupUi(self, equi_course_disp):
        equi_course_disp.setObjectName("equi_course_disp")
        equi_course_disp.resize(1068, 872)
        self.centralwidget = QtGui.QWidget(equi_course_disp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commandLinkButton = QtGui.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout.addWidget(self.commandLinkButton)
        self.label_groupbox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_groupbox.sizePolicy().hasHeightForWidth())
        self.label_groupbox.setSizePolicy(sizePolicy)
        self.label_groupbox.setMinimumSize(QtCore.QSize(0, 75))
        self.label_groupbox.setTitle("")
        self.label_groupbox.setObjectName("label_groupbox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.label_groupbox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.school1_label = QtGui.QLabel(self.label_groupbox)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.school1_label.setFont(font)
        self.school1_label.setObjectName("school1_label")
        self.verticalLayout_3.addWidget(self.school1_label)
        self.dept1_label = QtGui.QLabel(self.label_groupbox)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setWeight(75)
        font.setBold(True)
        self.dept1_label.setFont(font)
        self.dept1_label.setObjectName("dept1_label")
        self.verticalLayout_3.addWidget(self.dept1_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.arrow_label = QtGui.QLabel(self.label_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrow_label.sizePolicy().hasHeightForWidth())
        self.arrow_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setWeight(75)
        font.setBold(True)
        self.arrow_label.setFont(font)
        self.arrow_label.setObjectName("arrow_label")
        self.horizontalLayout_2.addWidget(self.arrow_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.school2_label = QtGui.QLabel(self.label_groupbox)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.school2_label.setFont(font)
        self.school2_label.setObjectName("school2_label")
        self.verticalLayout_4.addWidget(self.school2_label)
        self.dept2_label = QtGui.QLabel(self.label_groupbox)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setWeight(75)
        font.setBold(True)
        self.dept2_label.setFont(font)
        self.dept2_label.setObjectName("dept2_label")
        self.verticalLayout_4.addWidget(self.dept2_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.label_groupbox)
        self.list_groupbox = QtGui.QGroupBox(self.centralwidget)
        self.list_groupbox.setTitle("")
        self.list_groupbox.setObjectName("list_groupbox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.list_groupbox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtGui.QListWidget(self.list_groupbox)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.textBrowser_2 = QtGui.QListWidget(self.list_groupbox)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_3.addWidget(self.textBrowser_2)
        self.verticalLayout.addWidget(self.list_groupbox)
        self.button_groupbox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_groupbox.sizePolicy().hasHeightForWidth())
        self.button_groupbox.setSizePolicy(sizePolicy)
        self.button_groupbox.setMinimumSize(QtCore.QSize(0, 150))
        self.button_groupbox.setTitle("")
        self.button_groupbox.setObjectName("button_groupbox")
        self.gridLayout = QtGui.QGridLayout(self.button_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.back_button = QtGui.QToolButton(self.button_groupbox)
        self.back_button.setEnabled(True)
        self.back_button.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 1, 0, 1, 1)
        self.close_button = QtGui.QToolButton(self.button_groupbox)
        self.close_button.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.gridLayout.addWidget(self.close_button, 3, 0, 1, 1)
        self.content_button = QtGui.QToolButton(self.button_groupbox)
        self.content_button.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.content_button.setFont(font)
        self.content_button.setObjectName("content_button")
        self.gridLayout.addWidget(self.content_button, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.button_groupbox)
        equi_course_disp.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(equi_course_disp)
        self.statusbar.setObjectName("statusbar")
        equi_course_disp.setStatusBar(self.statusbar)

        self.retranslateUi(equi_course_disp)
        QtCore.QMetaObject.connectSlotsByName(equi_course_disp)

    def retranslateUi(self, equi_course_disp):
        equi_course_disp.setWindowTitle(QtGui.QApplication.translate("equi_course_disp", "Denk olan dersler listesi", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("equi_course_disp", "Tekrar Üniversite ve Bölüm seçimi için tıklayınız", None, QtGui.QApplication.UnicodeUTF8))
        self.school1_label.setText(QtGui.QApplication.translate("equi_course_disp", "First School", None, QtGui.QApplication.UnicodeUTF8))
        self.dept1_label.setText(QtGui.QApplication.translate("equi_course_disp", "First Dept", None, QtGui.QApplication.UnicodeUTF8))
        self.arrow_label.setText(QtGui.QApplication.translate("equi_course_disp", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">&gt;</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.school2_label.setText(QtGui.QApplication.translate("equi_course_disp", "Second School", None, QtGui.QApplication.UnicodeUTF8))
        self.dept2_label.setText(QtGui.QApplication.translate("equi_course_disp", "Second Dept", None, QtGui.QApplication.UnicodeUTF8))
        self.back_button.setText(QtGui.QApplication.translate("equi_course_disp", "Geri Dön", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("equi_course_disp", "Çıkış", None, QtGui.QApplication.UnicodeUTF8))
        self.content_button.setText(QtGui.QApplication.translate("equi_course_disp", "Ders İçeriğini Göster", None, QtGui.QApplication.UnicodeUTF8))

