# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Thu Apr 19 20:52:20 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 661)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox2.setEnabled(True)
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.school2_label = QtGui.QLabel(self.groupBox2)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.school2_label.setFont(font)
        self.school2_label.setObjectName("school2_label")
        self.verticalLayout_2.addWidget(self.school2_label)
        self.school2_list = QtGui.QComboBox(self.groupBox2)
        self.school2_list.setObjectName("school2_list")
        self.verticalLayout_2.addWidget(self.school2_list)
        self.dept2_label = QtGui.QLabel(self.groupBox2)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setWeight(75)
        font.setBold(True)
        self.dept2_label.setFont(font)
        self.dept2_label.setMargin(0)
        self.dept2_label.setObjectName("dept2_label")
        self.verticalLayout_2.addWidget(self.dept2_label)
        self.dept2_list = QtGui.QComboBox(self.groupBox2)
        self.dept2_list.setObjectName("dept2_list")
        self.verticalLayout_2.addWidget(self.dept2_list)
        self.gridLayout.addWidget(self.groupBox2, 0, 1, 1, 1)
        self.groupBox1 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox1.setEnabled(True)
        self.groupBox1.setTitle("")
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.school1_label = QtGui.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.school1_label.setFont(font)
        self.school1_label.setObjectName("school1_label")
        self.verticalLayout.addWidget(self.school1_label)
        self.school1_list = QtGui.QComboBox(self.groupBox1)
        self.school1_list.setObjectName("school1_list")
        self.verticalLayout.addWidget(self.school1_list)
        self.dept1_label = QtGui.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setWeight(75)
        font.setBold(True)
        self.dept1_label.setFont(font)
        self.dept1_label.setMargin(0)
        self.dept1_label.setObjectName("dept1_label")
        self.verticalLayout.addWidget(self.dept1_label)
        self.dept1_list = QtGui.QComboBox(self.groupBox1)
        self.dept1_list.setObjectName("dept1_list")
        self.verticalLayout.addWidget(self.dept1_list)
        self.gridLayout.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.compareGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.compareGroupBox.setTitle("")
        self.compareGroupBox.setObjectName("compareGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.compareGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.compare_button = QtGui.QPushButton(self.compareGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compare_button.sizePolicy().hasHeightForWidth())
        self.compare_button.setSizePolicy(sizePolicy)
        self.compare_button.setMinimumSize(QtCore.QSize(140, 70))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.compare_button.setFont(font)
        self.compare_button.setObjectName("compare_button")
        self.gridLayout_2.addWidget(self.compare_button, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.compareGroupBox, 3, 0, 1, 2)
        self.progress_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        self.progress_label.setFont(font)
        self.progress_label.setText("")
        self.progress_label.setObjectName("progress_label")
        self.gridLayout.addWidget(self.progress_label, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Kredi Transfer Denklik Sistemi", None, QtGui.QApplication.UnicodeUTF8))
        self.school2_label.setText(QtGui.QApplication.translate("MainWindow", "İkinci okulu seçin", None, QtGui.QApplication.UnicodeUTF8))
        self.dept2_label.setText(QtGui.QApplication.translate("MainWindow", "Bölümü seçin", None, QtGui.QApplication.UnicodeUTF8))
        self.school1_label.setText(QtGui.QApplication.translate("MainWindow", "İlk okulu seçin", None, QtGui.QApplication.UnicodeUTF8))
        self.dept1_label.setText(QtGui.QApplication.translate("MainWindow", "Bölümü seçin", None, QtGui.QApplication.UnicodeUTF8))
        self.compare_button.setText(QtGui.QApplication.translate("MainWindow", "Karşılaştır", None, QtGui.QApplication.UnicodeUTF8))

